apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conan-server.fullname" . }}
  labels:
    {{- include "conan-server.labels" . | nindent 4 }}
data:
  server.conf: |
    [server]
    jwt_secret: IJKhyoioUINMXCRTytrR
    jwt_expire_minutes: 120
    
    port: {{ .Values.service.targetPort }}
    public_port: {{ .Values.service.port }}
    
    disk_storage_path: /data
    
    [users]
    {{ .Values.configFile.users }}
    
    [read_permissions]
    {{ .Values.configFile.readPermissions }}
    
    [write_permissions]
    {{ .Values.configFile.writePermissions }}
